# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 07:28
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    for row in Expense.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
