# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20170816_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
