# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170526_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
