# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 06:49
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Contact = apps.get_model('users', 'Contact')
    for row in Contact.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
