# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=48, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('to', 'to'), ('by', 'by')], default='to', max_length=2)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=48, null=True, unique=True)),
                ('photo_url', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linked_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_contacts', to='transactions.User'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.User'),
        ),
    ]
