# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='transactioninformation',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
