# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20170216_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioninformation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_transactions', to='transactions.User'),
            preserve_default=False,
        ),
    ]
