# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170612_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='acknowledged_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
