# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20170216_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_id',
        ),
    ]
