# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_contact_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, unique=True),
        ),
    ]
