# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_acknowledged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
