# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-14 06:49
from __future__ import unicode_literals

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    for row in Transaction.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid)
    ]
