# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20170814_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
